runtime: python39
service: demeter

instance_class: B2

basic_scaling:
  max_instances: 2
  idle_timeout: 10m

entrypoint: gunicorn -b :$PORT -b :2222 -t 600 -w 1 main:app
handlers:
- url: /.*
  script: main.app
